### ISSUE TITLE
Can't install module with Yarn 3.x (berry)

### ISSUE THREAD

**Issue by FezVrasta** [aredridel/node-bin-gen#139]
We have #44 but it's about Yarn 1 I think.

`yarn add node` results in an error with the following logs:

```
# This file contains the result of Yarn building a package (node@npm:14.18.1)
# Script name: preinstall

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/Users/federicozivolo/Projects/app/node_modules/node/bin/node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I think the problem is that Yarn 3.x runs `preinstall` hooks as part of the `postinstall` cycle.

https://yarnpkg.com/advanced/lifecycle-scripts#:~:text=For%20backwards%20compatibility%2C-,preinstall,-and%20install%20are

I'm on macOS 11.6 running Node.js 14.18.1

**Comment by zauni** [comment]
Probably it would help to switch to the approach which [esbuild](https://github.com/evanw/esbuild) uses and instead of using a post-install script, using the optionalDependencies: https://github.com/evanw/esbuild/pull/1621

Maybe this could prevent a lot of edge cases?

But then the different node packages (operating-systems, CPU combinations) must be available on npm as seperate packages...

**Comment by manoraj** [comment]
I also have this issue in the yarn repository I am working on. For my use case, I had to use https://dotslash-cli.com/ instead of this package.

Considering yarn is the popular package manager, not a bad idea to support this to increase adoption.

**Comment by aredridel** [comment]
Yeah, the reason I haven't done what esbuild does is that adding more architectures or OSes later is impossible, since they have to be listed.

**Comment by aredridel** [comment]
> Considering yarn is the popular package manager, not a bad idea to support this to increase adoption.

Increasing adoption for increasing adoption's sake is a non-goal.
