### ISSUE TITLE
Facing http-parser error when i run command ng serve

### ISSUE THREAD

**Issue by Ejazashraftriplek** [aredridel/node-bin-gen#244]
ng serve
- Generating browser application bundles...(node:12988) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is de
(Use `node --trace-deprecation ...` to show where the warning was created)
\ Generating browser application bundles (phase: building)...node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@angular-devkit\build-angular\node_moduk\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@angular-devkit\build-anguodules\webpack\lib\NormalModule.js:417:16)
    at E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\le.js:452:10
    at E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\le.js:323:13
    at E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\loader-runner\lib\LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@ngtools\webpack\ss\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:739:10)
    at E:\Triple K Technology\New Clone\CandidatePortalFrontEnd\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.20.0

**Comment by aredridel** [comment]
This seems unrelated to this repository. Why do you think it belongs here?

**Comment by jazz3880** [comment]
https://github.com/aredridel/node-bin-gen/issues/244#issue-2212714323

**Comment by aredridel** [comment]
This is not related to this code or repository in any way.
