### ISSUE TITLE
cannot install node@0.10

### ISSUE THREAD

**Issue by teppeis** [aredridel/node-bin-gen#56]
```console
$ npm i node@0.10                                                                                                           [~/tmp/npm-node]

> node@0.10.48 preinstall /Users/teppeis/tmp/npm-node/node_modules/node
> node installArchSpecificPackage

npm ERR! code ETARGET
npm ERR! notarget No matching version found for node-darwin-x64@0.10.48
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/teppeis/.npm/_logs/2019-01-07T14_28_46_487Z-debug.log
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'node-darwin-x64/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at ChildProcess.<anonymous> (/Users/teppeis/tmp/npm-node/node_modules/node-bin-setup/index.js:18:27)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm WARN npm-node@1.0.0 No description
npm WARN npm-node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@0.10.48 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node@0.10.48 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/teppeis/.npm/_logs/2019-01-07T14_28_46_527Z-debug.log
```

The latest version of Node.js v0.10.x is [v0.10.48](https://nodejs.org/dist/latest-v0.10.x/) and [node@0.10.48](https://www.npmjs.com/package/node/v/0.10.48) is published correctly.
But [node-darwin-x64](https://www.npmjs.com/package/node-darwin-x64) doesn't have v0.10.48, the latest v0.10.x version is v0.10.47 and `v0.10-latest` tag is v0.10.46.
Also [node-linux-x64](https://www.npmjs.com/package/node-linux-x64)'s latest v0.10.x version and `v0.10-latest` tag is v0.10.46.

Please publish node-darwin-x64@0.10.48 and node-linux-x64@0.10.48.

**Comment by aredridel** [comment]
Doing so now. Thank you!

**Comment by teppeis** [comment]
@aredridel Thanks!
