### ISSUE TITLE
Cannot find module 'node-linux-arm/package.json'

### ISSUE THREAD

**Issue by brunocerk** [aredridel/node-bin-gen#59]
Nodejs Version: v11.9.0
Platform: Linux alarmpi 4.14.97-1-ARCH #1 SMP Tue Feb 5 20:10:34 UTC 2019 armv7l GNU/Linux

How to reproduce on my system: 
npm init
npm install node --save

Or npm install on any existing project

```
npm install node --save

node@11.9.0 preinstall /home/xxxxxx/testproject/node_modules/node
node installArchSpecificPackage

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/node-linux-arm - Not found
npm ERR! 404 
npm ERR! 404  'node-linux-arm@11.9.0' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxxx/.npm/_logs/2019-02-12T02_27_55_734Z-debug.log
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module 'node-linux-arm/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.resolve (internal/modules/cjs/helpers.js:28:19)
    at ChildProcess.<anonymous> (/home/xxxxxx/testproject/node_modules/node-bin-setup/index.js:18:27)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm WARN testproject@1.0.0 No description
npm WARN testproject@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@11.9.0 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node@11.9.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxxx/.npm/_logs/2019-02-12T02_27_55_840Z-debug.log

```

**Comment by psycr0w13** [comment]
Hey Guys,
I got the same problem --> I want to install my docker container which has node in its package.json on a raspbian stretch lite Raspberry Pi via yarn/npm install and get the same error:

`error /usr/src/app/node_modules/node: Command failed.
Exit code: 1
Command: node installArchSpecificPackage
Arguments: 
Directory: /usr/src/app/node_modules/node
Output:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.yarnpkg.com/node-linux-arm - Not found
npm ERR! 404 
npm ERR! 404  'node-linux-arm@12.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-07T08_24_01_424Z-debug.log
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'node-linux-arm/package.json'
Require stack:
- /usr/src/app/node_modules/node/installArchSpecificPackage.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/node-bin-setup/index.js:18:27)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
`

The answer describes really nice what the problem is, but how can I solve this? I need to install node in the docker container when building it. I found a way to install node globally on my Pi, but how can I install it in my container when building it on the Pi?

It would be so great if anybody could help me.
Thank you very much in advance :)

**Comment by VadneyK** [comment]
similar issue with M1 chip: https://github.com/aredridel/node-bin-gen/issues/124

**Comment by VadneyK** [comment]
View the solution to the similar issue: https://github.com/aredridel/node-bin-gen/issues/124

**Comment by VadneyK** [comment]
We really need this issue resolved: https://github.com/aredridel/node-bin-gen/issues/126

**Comment by mdarfay** [comment]
Any update on the issue ? Just trying to install an existing project on a Raspberry Pi 3 and got the same error (architecture being `armv7l`.

**Comment by StefanLobbenmeier** [comment]
Somehow there is already a discussion about this fix but not linked to here:
https://github.com/aredridel/node-bin-gen/issues/57
https://github.com/aredridel/node-bin-setup/pull/2
