### ISSUE TITLE
subpackage installation does not always inherit credentials for the registry

### ISSUE THREAD

**Issue by sonofhammer** [aredridel/node-bin-gen#60]
**Symptom** 
When using private npm registry, on win10, x64 environment the `node-win-x64` npm package will fail to install with a 401 error.

**Environment Specifics**
_This was initially discovered in a CI environment using a Private Build agent in Azure DevOps Pipelines, but can be reproduced outside of the CI environment._
This was tried and tested across several Node and npm versions.

**Root Cause**
The `npm install` that is executed inside `installArchSpecificPackage` fails because it does not use the registry credentials stored in the project's `.npmrc` file 

**To Reproduce**
1. Create a private registry of npm packages (I used [Azure Artifacts](https://azure.microsoft.com/en-us/services/devops/artifacts/)) (and populate it with the appropriate packages)
2. Create a directory for your project, in it, configure the `.npmrc` to point to the private registry.
3. Do not configure your private registry credentials in the `.npmrc` file inside the users home directory. or any other [three .npmrc files](https://docs.npmjs.com/files/npmrc)
4. Instead write out the credentials into the `.npmrc` file inside the project. (this is was Azure Pipelines does it on the Build agent. See [NPM Authenticate](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops) and [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops) for more info.)
5. run `npm install node`
6. observe authentication error for `node-win-x64`

**Workarounds**
1. Populate the `.npmrc` in the home directory with the credentials.
2. Poplulate the `NPM_CONFIG_USERCONFIG` environment variable with path of .npmrc that has the credentials. 

Both of these are undesirable because the project's `package.json` and `.npmrc` should be all that is needed to install all of the needed npm packages. from either public or private npm registries.

Verbose log output below

```
PS C:\src> npm install node --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'node',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v10.15.2
npm verb npm-session 8bb482269c29a83c
npm http fetch GET 200 https://pkgs.dev.azure.com/myproject_packaging/MyArtifacts/npm/registry/node 468ms
npm http fetch GET 200 https://pkgs.dev.azure.com/myproject_packaging/MyArtifacts/npm/registry/node/-/node-10.15.2.tgz 608ms
npm timing stage:loadCurrentTree Completed in 1903ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 14ms
npm http fetch GET 200 https://pkgs.dev.azure.com/myproject_packaging/MyArtifacts/npm/registry/node-bin-setup 222ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 245ms
npm timing stage:loadIdealTree Completed in 268ms
npm timing stage:generateActionsToTake Completed in 11ms
npm verb correctMkdir C:\Users\MyUser\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm timing audit compress Completed in 10ms
npm info audit Submitting payload of 247bytes
npm verb lock using C:\Users\MyUser\AppData\Roaming\npm-cache\_locks\staging-382712a43da04e93.lock for C:\src\node_modules\.staging
npm timing action:extract Completed in 75ms
npm http fetch POST 400 https://pkgs.dev.azure.com/myproject_packaging/MyArtifacts/npm/registry/-/npm/v1/security/audits/quick 297ms
npm timing action:finalize Completed in 44ms
npm timing action:refresh-package-json Completed in 55ms
npm info lifecycle node-bin-setup@1.0.6~preinstall: node-bin-setup@1.0.6
npm info lifecycle node@10.15.2~preinstall: node@10.15.2

> node@10.15.2 preinstall C:\src\node_modules\node
> node installArchSpecificPackage

npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'prefix',
npm verb cli   '-g' ]
npm info using npm@6.4.1
npm info using node@v10.15.2
npm verb exit [ 0, true ]
npm timing npm Completed in 816ms
npm info ok
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--no-save',
npm verb cli   'node-win-x64@10.15.2' ]
npm info using npm@6.4.1
npm info using node@v10.15.2
npm verb npm-session 8b26d976588dc0f8
npm http fetch GET 401 https://pkgs.dev.azure.com/myproject_packaging/MyArtifacts/npm/registry/node-win-x64 220ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 938ms
npm verb stack Error: 401 Unauthorized: node-win-x64@10.15.2
npm verb stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:705:18)
npm verb stack     at tryOnImmediate (timers.js:676:5)
npm verb stack     at processImmediate (timers.js:658:5)
npm verb cwd C:\src\node_modules\node
npm verb Windows_NT 10.0.17763
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-save" "node-win-x64@10.15.2"
npm verb node v10.15.2
npm verb npm  v6.4.1
npm ERR! code E401
npm ERR! 401 Unauthorized: node-win-x64@10.15.2
npm verb exit [ 1, true ]
npm timing npm Completed in 2782ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyUser\AppData\Roaming\npm-cache\_logs\2019-03-05T19_53_50_385Z-debug.log
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'node-win-x64/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at ChildProcess.<anonymous> (C:\src\node_modules\node-bin-setup\index.js:18:27)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb lifecycle node@10.15.2~preinstall: unsafe-perm in lifecycle true
npm verb lifecycle node@10.15.2~preinstall: PATH: [REDACTED]
npm verb lifecycle node@10.15.2~preinstall: CWD: C:\src\node_modules\node
npm info lifecycle node@10.15.2~preinstall: Failed to exec preinstall script
npm timing action:preinstall Completed in 6118ms
npm verb unlock done using C:\Users\MyUser\AppData\Roaming\npm-cache\_locks\staging-382712a43da04e93.lock for C:\src\node_modules\.staging
npm WARN rollback Rolling back node@10.15.2 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\src\node_modules'
npm timing stage:rollbackFailedOptional Completed in 21ms
npm timing stage:runTopLevelLifecycles Completed in 8791ms
npm WARN enoent ENOENT: no such file or directory, open 'C:\src\package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent
npm WARN src No description
npm WARN src No repository field.
npm WARN src No README data
npm WARN src No license field.

npm verb stack Error: node@10.15.2 preinstall: `node installArchSpecificPackage`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid node@10.15.2
npm verb cwd C:\src
npm verb Windows_NT 10.0.17763
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node" "--verbose"
npm verb node v10.15.2
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@10.15.2 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node@10.15.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 10768ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyUser\AppData\Roaming\npm-cache\_logs\2019-03-05T19_53_50_761Z-debug.log
```

**Comment by VadneyK** [comment]
checkout solution to related issues here: https://github.com/aredridel/node-bin-gen/issues/124

**Comment by VadneyK** [comment]
We really need this issue resolved: https://github.com/aredridel/node-bin-gen/issues/126

**Comment by aredridel** [comment]
Does this still happen with current npm and node?

**Comment by Gerhut** [comment]
Yes

**Comment by aredridel** [comment]
Oh this is going to be interesting to fix. I need to figure out what normally injects those credentials and make sure the install script understands them or finds them.

**Comment by Gerhut** [comment]
My finding is that when running postinstall, the CWD is `./node_modules/node`, but not `.`, so `./.npmrc` does not provide credentials.

**Comment by KnisterPeter** [comment]
Doesn't work with latest `pnpm` 😢 

```shell
test@569090f72bd9:~/test$ pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +65
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 65, reused 65, downloaded 0, added 0, done
 WARN  Failed to create bin at /home/test/test/node_modules/.pnpm/node@24.0.1/node_modules/node/node_modules/.bin/node. ENOENT: no such file or directory, open '/home/test/test/node_modules/.pnpm/node@24.0.1/node_modules/node/bin/node'
node_modules/.pnpm/node@24.0.1/node_modules/node: Running preinstall script, failed in 1.4s
.../.pnpm/node@24.0.1/node_modules/node preinstall$ node installArchSpecificPackage
│ (node:158) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ npm warn Unknown env config "_pit-mlc-registry". This will stop working in the next major version of npm.
│ npm warn Unknown env config "_pit-shared-registry". This will stop working in the next major version of npm.
│ npm warn Unknown env config "verify-deps-before-run". This will stop working in the next major version of npm.
│ npm warn Unknown env config "_statista-registry". This will stop working in the next major version of npm.
│ npm warn Unknown env config "_jsr-registry". This will stop working in the next major version of npm.
│ npm warn Unknown env config "_pit-marketing-content-registry". This will stop working in the next major version of npm.
│ npm error code E403
│ npm error 403 403 Forbidden - GET https://npm.pkg.github.com/pit-shared/node-bin-setup - Permission denied
│ npm error 403 In most cases, you or one of your dependencies are requesting
│ npm error 403 a package version that is forbidden by your security policy, or
│ npm error 403 on a server you do not have access to.
│ npm error A complete log of this run can be found in: /home/test/.npm/_logs/2025-05-12T09_44_44_699Z-debug-0.log
│ node:internal/modules/cjs/loader:1408
│   throw err;
│   ^
│ Error: Cannot find module 'node-linux-x64/package.json'
│ Require stack:
│ - /home/test/test/node_modules/.pnpm/node@24.0.1/node_modules/node/installArchSpecificPackage.js
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1405:15)
│     at require.resolve (node:internal/modules/helpers:145:19)
│     at ChildProcess.<anonymous> (/home/test/test/node_modules/.pnpm/node-bin-setup@1.1.3/node_modules/node-bin-setup/index.js:19:27)
│     at ChildProcess.emit (node:events:507:28)
│     at maybeClose (node:internal/child_process:1101:16)
│     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     '/home/test/test/node_modules/.pnpm/node@24.0.1/node_modules/node/installArchSpecificPackage.js'
│   ]
│ }
│ Node.js v24.0.1
└─ Failed in 1.4s at /home/test/test/node_modules/.pnpm/node@24.0.1/node_modules/node
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by KnisterPeter** [comment]
To be more exact:
- In a setup with node@24 provided (related npm) running `pnpm add node@24` does **not** work.
- In a seutp with node@22 provided (related npm) running `pnpm add node@24` does work.

It seems latet npm does change somehow and forget the authentication stuff.

**Comment by aredridel** [comment]
Oh fascinating. I'm not sure how npm ends up involved, but pnpm's approach to things may require entirely different hacks.

**Comment by KnisterPeter** [comment]
It's not only about pnpm, it's with npm only as well as you can see here:

```shell
test@3f6c8386fe55:~/test$ npm i
npm warn Unknown project config "node-linker". This will stop working in the next major version of npm.
npm error code E404
npm error 404 Not Found - GET https://npm.pkg.github.com/aws-cdk-lib/-/aws-cdk-lib-2.195.0.tgz
npm error 404
npm error 404  'aws-cdk-lib@https://npm.pkg.github.com/aws-cdk-lib/-/aws-cdk-lib-2.195.0.tgz' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/test/.npm/_logs/2025-05-12T14_58_18_273Z-debug-0.log
test@3f6c8386fe55:~/test$ 
test@3f6c8386fe55:~/test$ 
test@3f6c8386fe55:~/test$ 
exit
markusw@STAT-HH-2367:~/source/statista/cdn-certificates (renovate/node-24.x)$ rm -rf node_modules/ .pnpm-store/ && docker run --rm -ti --init -v "$(pwd)":/home/test/test -v "$HOME/.npmrc:/home/test/.npmrc" test:test
test@e0db27f88480:~$ n install 22
  installing : node-v22.15.0
       mkdir : /usr/local/n/versions/node/22.15.0
       fetch : https://nodejs.org/dist/v22.15.0/node-v22.15.0-linux-x64.tar.xz
     copying : node/22.15.0
   installed : v22.15.0 (with npm 10.9.2)
test@e0db27f88480:~$ cd test
test@e0db27f88480:~/test$ npm i

added 64 packages in 52s

21 packages are looking for funding
  run `npm fund` for details
test@e0db27f88480:~/test$ 
```

Yet I don't understand why.
